import { Roboto } from 'next/font/google'
import "./globals.css";
import ClientProvider from '@/components/ClientProvider';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
export const metadata = {
  title: "Kelal English",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientProvider>
      <html lang="en">
        <body className={`${roboto.className}`}>{children}</body>
      </html>
    </ClientProvider>
  );
}
