import { Roboto } from 'next/font/google';
import "./globals.css";
import Header from '@/components/Header';
import ClientProvider from '@/components/ClientProvider';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: "Kelal English",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <div className="flex min-h-screen flex-col">
          <ClientProvider>
            <Header />
            <main className="flex flex-1 flex-col items-center justify-center">
              {children}
            </main>
            {/* <Footer /> */}
          </ClientProvider>
        </div>
      </body>
    </html>
  );
}
